name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.elm
            ~/.npm
            **/elm-stuff
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - name: Run Unit Tests
        run: npm test
      - name: Review Check
        run: npm run review:check
